name: Docker Image CI

# when to run 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:                               # execute a button to execute from outside of repo
    inputs:
      image_version:
        description: 'Please specify a verison'
        required: false
        default: "latest"
      tools-to-build:
        description: 'Please specify a tool'
        required: false
        default: "tools"





jobs:

  build:

    runs-on: ubuntu-latest



    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tools/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tools:latest



  terraform-build:

    runs-on: ubuntu-latest
    if: github.event.inputs.tools_to_build == '' || github.event.inputs.tools_to_build == 'tools'



    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./terraform/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/terraform:latest          